use_frameworks!

platform :ios, '10.0'

target 'WDBLEManager_Example' do
  pod 'WDBLEManager', :path => '../'

  target 'WDBLEManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
